set SEARCH_PATH = unc_251340;

CREATE TABLE TP_03_EJ_02_USUARIO(
	id_usuario INT NOT NULL,
	tipo_doc VARCHAR(10) NOT NULL,
	nro_doc BIGINT NOT NULL,
	apellido VARCHAR(40) NOT NULL,
	nombre VARCHAR(40) NOT NULL,
	e_mail VARCHAR(50) NOT NULL,
	tipo SMALLINT NOT NULL,
	CONSTRAINT PK_USUARIO PRIMARY KEY(id_usuario),
	CONSTRAINT U_IDENTIFICACION_USUARIO UNIQUE(tipo_doc, nro_doc),
	CONSTRAINT CH_USUARIO_TIPO_DOC CHECK((tipo_doc = 'DNI') OR (tipo_doc = 'PASAPORTE')),
	CONSTRAINT CH_USUARIO_NRO_DOC CHECK(nro_doc > 0),
	CONSTRAINT CK_USUARIO_TIPO CHECK(tipo IN (1, 2))
);

CREATE TABLE TP_03_EJ_02_SIN_CARNET(
	id_usuario INT NOT NULL,
	nro_celular VARCHAR(20) NOT NULL,
	CONSTRAINT PK_SIN_CARNET PRIMARY KEY(id_usuario),
	CONSTRAINT FK_SIN_CARNET_USUARIO FOREIGN KEY(id_usuario) REFERENCES TP_03_EJ_02_USUARIO(id_usuario)
);

CREATE TABLE TP_03_EJ_02_CON_CARNET(
	id_usuario INT NOT NULL,
	nro_carnet INT NOT NULL,
	CONSTRAINT PK_CON_CARNET PRIMARY KEY(id_usuario),
	CONSTRAINT FK_CON_CARNET_USUARIO FOREIGN KEY(id_usuario) REFERENCES TP_03_EJ_02_USUARIO(id_usuario),
	CONSTRAINT U_NRO_CARNET UNIQUE(nro_carnet)
)

CREATE TABLE TP_03_EJ_02_CATALOGO_LIBRO(
	cod_catalogo INT NOT NULL,
	titulo VARCHAR(30) NOT NULL,
	formato VARCHAR(30) NOT NULL,
	editorial VARCHAR(30) NOT NULL,
	CONSTRAINT PK_CATALOGO_LIBRO PRIMARY KEY(cod_catalogo)
);

CREATE TABLE TP_03_EJ_02_AUTOR(
	id_autor INT NOT NULL,
	nombre VARCHAR(40) NOT NULL,
	apellido VARCHAR(50) NOT NULL,
	CONSTRAINT PK_AUTOR PRIMARY KEY(id_autor)
);

CREATE TABLE TP_03_EJ_02_AUTOR_CATALOGO_LIBRO(
	cod_catalogo INT NOT NULL,
	id_autor INT NOT NULL,
	CONSTRAINT PK_AUTOR_CATALOGO_LIBRO PRIMARY KEY(cod_catalogo, id_autor),
	CONSTRAINT FK_AUTOR_CATALOGO_LIBRO_AUTOR FOREIGN KEY(id_autor) REFERENCES TP_03_EJ_02_AUTOR(id_autor),
	CONSTRAINT FK_AUTOR_CATALOGO_LIBRO_CATALOGO_LIBRO FOREIGN KEY(cod_catalogo) REFERENCES TP_03_EJ_02_CATALOGO_LIBRO(cod_catalogo)
);

CREATE TABLE TP_03_EJ_02_EJEMPLAR_LIBRO(
	nro_ejemplar INT NOT NULL,
	cod_catalogo INT NOT NULL,
	anio_edicion INT NOT NULL,
	nro_edicion INT NOT NULL,
	CONSTRAINT PK_EJEMPLAR_LIBRO PRIMARY KEY(nro_ejemplar),
	CONSTRAINT FK_EJEMPLAR_LIBRO_CATALOGO_LIBRO FOREIGN KEY(cod_catalogo) REFERENCES TP_03_EJ_02_CATALOGO_LIBRO(cod_catalogo),
	CONSTRAINT CH_EJEMPLAR_LIBRO_ANIO_EDICION CHECK (anio_edicion > 0),
	CONSTRAINT CH_EJEMPLAR_LIBRO_NRO_EDICION CHECK (nro_edicion > 0)
);

CREATE TABLE TP_03_EJ_02_PRESTAMO(
	id_prestamo INT NOT NULL,
	fecha_desde DATE NOT NULL,
	fecha_hasta DATE NOT NULL,
	CONSTRAINT PK_PRESTAMO PRIMARY KEY(id_prestamo),
	CONSTRAINT CH_PRESTAMO_FECHA_DESDE CHECK(fecha_desde <= fecha_hasta)
);

CREATE TABLE TP_03_EJ_02_PRESTAMO_EJEMPLAR_LIBRO(
	id_prestamo INT NOT NULL,
	nro_ejemplar INT NOT NULL,
	nro_carnet INT NOT NULL,
	CONSTRAINT PK_PRESTAMO_EJEMPLAR_LIBRO PRIMARY KEY(id_prestamo, nro_ejemplar),
	CONSTRAINT FK_PRESTAMO_EJEMPLAR_LIBRO_PRESTAMO FOREIGN KEY(id_prestamo) REFERENCES TP_03_EJ_02_PRESTAMO(id_prestamo),
	CONSTRAINT FK_PRESTAMO_EJEMPLAR_LIBRO_EJEMPLAR_LIBRO FOREIGN KEY(nro_ejemplar) REFERENCES TP_03_EJ_02_EJEMPLAR_LIBRO(nro_ejemplar),
	CONSTRAINT FK_PRESTAMO_EJEMPLAR_LIBRO_CON_CARNET FOREIGN KEY(nro_carnet) REFERENCES TP_03_EJ_02_CON_CARNET(nro_carnet)
);