SET SEARCH_PATH = unc_251340;

CREATE TABLE TP_03_EJ_03_CLIENTE(
	id_cliente INT NOT NULL,
	CUIT BIGINT NOT NULL,
	id_garante INT DEFAULT NULL,
	apellido VARCHAR(50) NOT NULL,
	nombre VARCHAR(50) NOT NULL,
	calle VARCHAR(50) NOT NULL,
	puerta INT NOT NULL,
	piso INT NOT NULL,
	e_mail VARCHAR(70),
	telefono VARCHAR(20) NOT NULL,
	CONSTRAINT PK_CLIENTE PRIMARY KEY (id_cliente)
);

CREATE TABLE TP_03_EJ_03_PRODUCTO_QUIMICO(
	id_prod_quim INT NOT NULL,
	nombre_prod_quim VARCHAR(100) NOT NULL,
	formula VARCHAR(10) NOT NULL,
	tipo_pq VARCHAR NOT NULL,
	CONSTRAINT PK_PRODUCTO_QUIMICO PRIMARY KEY(id_prod_quim),
	CONSTRAINT CH_PRODUCTO_QUIMICO_TIPO CHECK(tipo_pq IN('solido','liquido'))
);


CREATE TABLE TP_03_EJ_03_ENVIO(
	nro_envio INT NOT NULL,
	id_cliente INT NOT NULL,
	id_prod_quim INT NOT NULL,
	cantidad INT NOT NULL,
	peso_grms INT NOT NULL,
	CONSTRAINT PK_ENVIO PRIMARY KEY(nro_envio),
	CONSTRAINT FK_ENVIO_CLIENTE FOREIGN KEY(id_cliente) REFERENCES TP_03_EJ_03_CLIENTE(id_cliente),
	CONSTRAINT FK_ENVIO_PRODUCTO_QUIMICO FOREIGN KEY(id_prod_quim) REFERENCES TP_03_EJ_03_PRODUCTO_QUIMICO(id_prod_quim),
	CONSTRAINT CH_ENVIO_NRO_ENVIO_POSITIVO CHECK(nro_envio > 0),
	CONSTRAINT CH_ENVIO_CANTIDAD CHECK(cantidad > 0),
	CONSTRAINT CH_ENVIO_PESO_GRMS CHECK(peso_grms > 0)
);

CREATE TABLE TP_03_EJ_03_PRODUCTO_QUIMICO_COMPONE(
	id_prod_quim INT NOT NULL,
	id_prod_quim_agregado INT NOT NULL,
	porcentaje SMALLINT NOT NULL,
	CONSTRAINT PK_PRODUCTO_QUIMICO_COMPONE PRIMARY KEY(id_prod_quim, id_prod_quim_agregado),
	CONSTRAINT FK_PRODUCTO_QUIMICO_RESULTANTE FOREIGN KEY(id_prod_quim) REFERENCES TP_03_EJ_03_PRODUCTO_QUIMICO(id_prod_quim),
	CONSTRAINT FK_PRODUCTO_QUIMICO_PORCENTAJE FOREIGN KEY(id_prod_quim_agregado) REFERENCES TP_03_EJ_03_PRODUCTO_QUIMICO(id_prod_quim)
);

CREATE TABLE TP_03_EJ_03_PQ_LIQUIDO(
	id_prod_quim INT NOT NULL,
	inflamable BOOLEAN NOT NULL,
	tipo_envase VARCHAR(30) NOT NULL,
	cond_translado VARCHAR(40),
	CONSTRAINT PK_PQ_LIQUIDO PRIMARY KEY(id_prod_quim),
	CONSTRAINT FK_PQ_LIQUIDO_PRODUCTO_QUIMICO FOREIGN KEY(id_prod_quim) REFERENCES TP_03_EJ_03_PRODUCTO_QUIMICO(id_prod_quim)
);

CREATE TABLE TP_03_EJ_03_PQ_SOLIDO(
	id_prod_quim INT NOT NULL,
	forma VARCHAR(30) NOT NULL,
	empaque_max INT NOT NULL,
	CONSTRAINT PK_PQ_SOLIDO PRIMARY KEY(id_prod_quim),
	CONSTRAINT FK_PQ_SOLIDO_PRODUCTO_QUIMICO FOREIGN KEY(id_prod_quim) REFERENCES TP_03_EJ_03_PRODUCTO_QUIMICO(id_prod_quim),
	CONSTRAINT CH_PQ_SOLIDO_EMPAQUE_MAX CHECK(empaque_max > 0)
);