set SEARCH_PATH = unc_251340;

CREATE TABLE TP_03_EJ01_REPOSITORIO(
	ID_REPOSITORIO INT NOT NULL,
	NOMBRE VARCHAR(40) NOT NULL,
	PUBLICO BOOLEAN NOT NULL,
	DESCRIPCION VARCHAR(255) NOT NULL,
	DUENIO VARCHAR(30),
	CONSTRAINT PK_REPOSITORIO PRIMARY KEY(ID_REPOSITORIO)
);

CREATE TABLE TP_03_EJ01_COLECCION(
	ID_COLECCION INT NOT NULL,
	TITULO_COLECCION VARCHAR(30) NOT NULL,
	DESCRIPCION VARCHAR(255) NOT NULL,
	CONSTRAINT PK_COLECCION PRIMARY KEY(ID_COLECCION)
);

CREATE TABLE TP_03_EJ01_OBJETO(
	ID_OBJETO INT NOT NULL,
	ID_COLECCION INT NOT NULL,
	ID_REPOSITORIO INT NOT NULL,
	TITULO VARCHAR(30) NOT NULL,
	DESCRIPCION VARCHAR (255) NOT NULL,
	FUENTE VARCHAR(30) NOT NULL,
	FECHA DATE NOT NULL,
	TIPO CHAR NOT NULL,
	CONSTRAINT PK_OBJETO PRIMARY KEY(ID_OBJETO, ID_COLECCION),
	CONSTRAINT FK_OBJETO_COLECCION FOREIGN KEY (ID_COLECCION) REFERENCES TP_03_EJ01_COLECCION(ID_COLECCION),
	CONSTRAINT FK_OBJETO_REPOSITORIO FOREIGN KEY (ID_REPOSITORIO) REFERENCES TP_03_EJ01_REPOSITORIO(ID_REPOSITORIO),
	CONSTRAINT CH_TIPO_OBJETO CHECK(TIPO IN('A', 'V', 'D'))
);

CREATE TABLE TP_03_EJ01_AUDIO(
	ID_OBJETO INT NOT NULL,
	ID_COLECCION INT NOT NULL,
	FORMATO VARCHAR(20) NOT NULL,
	DURACION_SEGS BIGINT NOT NULL,
	CONSTRAINT PK_AUDIO PRIMARY KEY(ID_OBJETO, ID_COLECCION),
	CONSTRAINT FK_AUDIO_OBJETO FOREIGN KEY(ID_OBJETO, ID_COLECCION) REFERENCES TP_03_EJ01_OBJETO(ID_OBJETO, ID_COLECCION)
);

CREATE TABLE TP_03_EJ01_VIDEO(
	ID_OBJETO INT NOT NULL,
	ID_COLECCION INT NOT NULL,
	RESOLUCION VARCHAR(20) NOT NULL,
	FRAMES_POR_SEGUNDO INT NOT NULL,
	CONSTRAINT PK_VIDEO PRIMARY KEY(ID_OBJETO, ID_COLECCION),
	CONSTRAINT FK_VIDEO_OBJETO FOREIGN KEY(ID_OBJETO, ID_COLECCION) REFERENCES TP_03_EJ01_OBJETO(ID_OBJETO, ID_COLECCION)
);

CREATE TABLE TP_03_EJ01_DOCUMENTO(
	ID_OBJETO INT NOT NULL,
	ID_COLECCION INT NOT NULL,
	TIPO_PUBLICACION VARCHAR(40) NOT NULL,
	MODOS_COLOR VARCHAR(30) NOT NULL,
	RESOLUCION_CAPTURA VARCHAR(20) NOT NULL,
	CONSTRAINT PK_DOCUMENTO PRIMARY KEY(ID_OBJETO, ID_COLECCION),
	CONSTRAINT FK_DOCUMENTO_OBJETO FOREIGN KEY(ID_OBJETO, ID_COLECCION) REFERENCES TP_03_EJ01_OBJETO(ID_OBJETO, ID_COLECCION)
);

DROP TABLE
    TP_03_EJ01_AUDIO,
    TP_03_EJ01_VIDEO,
    TP_03_EJ01_DOCUMENTO,
    TP_03_EJ01_OBJETO,
    TP_03_EJ01_REPOSITORIO,
    TP_03_EJ01_COLECCION;
